LOCAL_PATH := vendor/ZTE/MSM8974
PRODUCT_COPY_FILES += \

	$(LOCAL_PATH)/system/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
$(LOCAL_PATH)/system/bin/hotplug_cpu:system/bin/hotplug_cpu \
$(LOCAL_PATH)/system/bin/imsdatadaemon:system/bin/imsdatadaemon \
$(LOCAL_PATH)/system/bin/ims_rtp_daemon:system/bin/ims_rtp_daemon \
$(LOCAL_PATH)/system/bin/imsqmidaemon:system/bin/imsqmidaemon \
$(LOCAL_PATH)/system/bin/make_ext4fs:system/bin/make_ext4fs \
$(LOCAL_PATH)/system/bin/mm-audio-alsa-test:system/bin/mm-audio-alsa-test \
$(LOCAL_PATH)/system/bin/mm-audio-ftm:system/bin/mm-audio-ftm \
$(LOCAL_PATH)/system/bin/mm-qcamera-app:system/bin/mm-qcamera-app \
$(LOCAL_PATH)/system/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
$(LOCAL_PATH)/system/bin/mount.exfat:system/bin/mount.exfat \
$(LOCAL_PATH)/system/bin/ntfs-3g:system/bin/ntfs-3g \
$(LOCAL_PATH)/system/bin/qcom-system-daemon:system/bin/qcom-system-daemon \
$(LOCAL_PATH)/system/bin/qmiproxy:system/bin/qmiproxy \
$(LOCAL_PATH)/system/bin/qmi_simple_ril_test:system/bin/qmi_simple_ril_test \
$(LOCAL_PATH)/system/bin/radiooptions:system/bin/radiooptions \
$(LOCAL_PATH)/system/bin/reboot:system/bin/reboot \
$(LOCAL_PATH)/system/bin/rfc:system/bin/rfc \
$(LOCAL_PATH)/system/bin/rfs_access:system/bin/rfs_access \
$(LOCAL_PATH)/system/bin/rild:system/bin/rild \
$(LOCAL_PATH)/system/bin/sdcard:system/bin/sdcard \
$(LOCAL_PATH)/system/bin/sensorservice:system/bin/sensorservice \
$(LOCAL_PATH)/system/bin/sensors.qcom:system/bin/sensors.qcom \
$(LOCAL_PATH)/system/bin/settings:system/bin/settings \
$(LOCAL_PATH)/system/bin/surfaceflinger:system/bin/surfaceflinger \
$(LOCAL_PATH)/system/bin/thermald:system/bin/thermald \
$(LOCAL_PATH)/system/bin/thermal-engine:system/bin/thermal-engine \
$(LOCAL_PATH)/system/bin/thermal-ext:system/bin/thermal-ext \
$(LOCAL_PATH)/system/bin/time_daemon:system/bin/time_daemon \
$(LOCAL_PATH)/system/bin/vold:system/bin/vold \
$(LOCAL_PATH)/system/bin/wdsdaemon:system/bin/wdsdaemon \
$(LOCAL_PATH)/system/bin/wpa_cli:system/bin/wpa_cli \
$(LOCAL_PATH)/system/bin/wpa_supplicant:system/bin/wpa_supplicant \
$(LOCAL_PATH)/system/bin/xtwifi-client:system/bin/xtwifi-client \
$(LOCAL_PATH)/system/etc/apns-conf.xml:system/etc/apns-conf.xml \
$(LOCAL_PATH)/system/etc/audio_effects.conf:system/etc/audio_effects.conf \
$(LOCAL_PATH)/system/etc/audio_policy.conf:system/etc/audio_policy.conf \
$(LOCAL_PATH)/system/etc/gps.conf:system/etc/gps.conf \
$(LOCAL_PATH)/system/etc/init.qcom.fm.sh:system/etc/init.qcom.fm.sh \
$(LOCAL_PATH)/system/etc/init.qcom.modem_links.sh:system/etc/init.qcom.modem_links.sh \
$(LOCAL_PATH)/system/etc/init.qcom.post_boot.sh:system/etc/init.qcom.post_boot.sh \
$(LOCAL_PATH)/system/etc/init.qcom.sdio.sh:system/etc/init.qcom.sdio.sh \
$(LOCAL_PATH)/system/etc/init.qcom.wifi.sh:system/etc/init.qcom.wifi.sh \
$(LOCAL_PATH)/system/etc/izat.conf:system/etc/izat.conf \
$(LOCAL_PATH)/system/etc/p2p_supplicant_overlay.conf:system/etc/p2p_supplicant_overlay.conf \
$(LOCAL_PATH)/system/etc/vold.fstab:system/etc/vold.fstab \
$(LOCAL_PATH)/system/etc/wpa_supplicant_ath6kl.conf:system/etc/wpa_supplicant_ath6kl.conf \
$(LOCAL_PATH)/system/etc/wpa_supplicant.conf:system/etc/wpa_supplicant.conf \
$(LOCAL_PATH)/system/etc/wpa_supplicant_overlay.conf:system/etc/wpa_supplicant_overlay.conf \
$(LOCAL_PATH)/system/app/Ds/Ds.apk:system/app/Ds/Ds.apk \
$(LOCAL_PATH)/system/app/DsUI/DsUI.apk:system/app/DsUI/DsUI.apk \
$(LOCAL_PATH)/system/lib/egl/egl.cfg:system/lib/egl/egl.cfg \
$(LOCAL_PATH)/system/lib/egl/eglsubAndroid.so:system/lib/egl/eglsubAndroid.so \
$(LOCAL_PATH)/system/lib/egl/libEGL_adreno.so:system/lib/egl/libEGL_adreno.so \
$(LOCAL_PATH)/system/lib/egl/libGLESv1_CM_adreno.so:system/lib/egl/libGLESv1_CM_adreno.so \
$(LOCAL_PATH)/system/lib/egl/libGLESv2_adreno.so:system/lib/egl/libGLESv2_adreno.so \
$(LOCAL_PATH)/system/lib/egl/libq3dtools_adreno.so:system/lib/egl/libq3dtools_adreno.so \
$(LOCAL_PATH)/system/lib/hw/audio.a2dp.default.so:system/lib/hw/audio.a2dp.default.so \
$(LOCAL_PATH)/system/lib/hw/audio_policy.default.so:system/lib/hw/audio_policy.default.so \
$(LOCAL_PATH)/system/lib/hw/audio.primary.default.so:system/lib/hw/audio.primary.default.so \
$(LOCAL_PATH)/system/lib/hw/audio.primary.msm8974.so:system/lib/hw/audio.primary.msm8974.so \
$(LOCAL_PATH)/system/lib/hw/audio.r_submix.default.so:system/lib/hw/audio.r_submix.default.so \
$(LOCAL_PATH)/system/lib/hw/audio.usb.default.so:system/lib/hw/audio.usb.default.so \
$(LOCAL_PATH)/system/lib/hw/bluetooth.default.so:system/lib/hw/bluetooth.default.so \
$(LOCAL_PATH)/system/lib/hw/camera.msm8974.so.so:system/lib/hw/camera.msm8974.so \
$(LOCAL_PATH)/system/lib/hw/copybit.msm8974.so:system/lib/hw/copybit.msm8974.so \
$(LOCAL_PATH)/system/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
$(LOCAL_PATH)/system/lib/hw/gralloc.default.so:system/lib/hw/gralloc.default.so \
$(LOCAL_PATH)/system/lib/hw/gralloc.msm8974.so:system/lib/hw/gralloc.msm8974.so \
$(LOCAL_PATH)/system/lib/hw/hwcomposer.msm8974.so:system/lib/hw/hwcomposer.msm8974.so \
$(LOCAL_PATH)/system/lib/hw/keystore.default.so:system/lib/hw/keystore.default.so \
$(LOCAL_PATH)/system/lib/hw/libEGL.so:system/lib/hw/libEGL.so \
$(LOCAL_PATH)/system/lib/hw/libGLES_trace.so:system/lib/hw/libGLES_trace.so \
$(LOCAL_PATH)/system/lib/hw/libGLESv1_CM.so:system/lib/hw/libGLESv1_CM.so \
$(LOCAL_PATH)/system/lib/hw/libGLESv2.so:system/lib/hw/libGLESv2.so \
$(LOCAL_PATH)/system/lib/hw/lights.msm8974.so:system/lib/hw/lights.msm8974.so \
$(LOCAL_PATH)/system/lib/hw/local_time.default.so:system/lib/hw/local_time.default.so \
$(LOCAL_PATH)/system/lib/hw/memtrack.msm8974.so:system/lib/hw/memtrack.msm8974.so \
$(LOCAL_PATH)/system/lib/hw/power.default.so:system/lib/hw/power.default.so \
$(LOCAL_PATH)/system/lib/hw/power.qcom.so:system/lib/hw/power.qcom.so \
$(LOCAL_PATH)/system/lib/hw/sensors.msm8974.so:system/lib/hw/sensors.msm8974.so \
$(LOCAL_PATH)/system/lib/hw/vibrator.default.so:system/lib/hw/vibrator.default.so \
$(LOCAL_PATH)/system/lib/soundfx/libaudiopreprocessing.so:system/lib/soundfx/libaudiopreprocessing.so \
$(LOCAL_PATH)/system/lib/soundfx/libbundlewrapper.so:system/lib/soundfx/libbundlewrapper.so \
$(LOCAL_PATH)/system/lib/soundfx/libdownmix.so:system/lib/soundfx/libdownmix.so \
$(LOCAL_PATH)/system/lib/soundfx/libeffectproxy.so:system/lib/soundfx/libeffectproxy.so \
$(LOCAL_PATH)/system/lib/soundfx/libldnhncr.so:system/lib/soundfx/libldnhncr.so \
$(LOCAL_PATH)/system/lib/soundfx/libqcompostprocbundle.so:system/lib/soundfx/libqcompostprocbundle.so \
$(LOCAL_PATH)/system/lib/soundfx/libqcomvisualizer.so:system/lib/soundfx/libqcomvisualizer.so \
$(LOCAL_PATH)/system/lib/soundfx/libqcomvoiceprocessing.so:system/lib/soundfx/libqcomvoiceprocessing.so \
$(LOCAL_PATH)/system/lib/soundfx/libreverbwrapper.so:system/lib/soundfx/libreverbwrapper.so \
$(LOCAL_PATH)/system/lib/soundfx/libvisualizer.so:system/lib/soundfx/libvisualizer.so \
$(LOCAL_PATH)/system/lib/libaudioeffect_jni.so:system/lib/libaudioeffect_jni.so \
$(LOCAL_PATH)/system/lib/libaudioflinger.so:system/lib/libaudioflinger.so \
$(LOCAL_PATH)/system/lib/libaudioparameter.so:system/lib/libaudioparameter.so \
$(LOCAL_PATH)/system/lib/libaudiopolicymanagerdefault.so:system/lib/libaudiopolicymanagerdefault.so \
$(LOCAL_PATH)/system/lib/libaudiopolicymanager.so:system/lib/libaudiopolicymanager.so \
$(LOCAL_PATH)/system/lib/libaudiopolicyservice.so:system/lib/libaudiopolicyservice.so \
$(LOCAL_PATH)/system/lib/libaudio-resampler.so:system/lib/libaudio-resampler.so \
$(LOCAL_PATH)/system/lib/libaudioresampler.so:system/lib/libaudioresampler.so \
$(LOCAL_PATH)/system/lib/libaudioroute.so:system/lib/libaudioroute.so \
$(LOCAL_PATH)/system/lib/libaudioutils.so:system/lib/libaudioutils.so \
$(LOCAL_PATH)/system/lib/libbluetooth_jni.so:system/lib/libbluetooth_jni.so \
$(LOCAL_PATH)/system/lib/libbt-vendor.so:system/lib/libbt-vendor.so \
$(LOCAL_PATH)/system/lib/libcamera_client.so:system/lib/libcamera_client.so \
$(LOCAL_PATH)/system/lib/libcamera_metadata.so:system/lib/libcamera_metadata.so \
$(LOCAL_PATH)/system/lib/libcameraservice.so:system/lib/libcameraservice.so \
$(LOCAL_PATH)/system/lib/libchromatix_imx135_liveshot.so:system/lib/libchromatix_imx135_liveshot.so \
$(LOCAL_PATH)/system/lib/libc.so:system/lib/libc.so \
$(LOCAL_PATH)/system/lib/libcutils.so:system/lib/libcutils.so \
$(LOCAL_PATH)/system/lib/libdl.so:system/lib/libdl.so \
$(LOCAL_PATH)/system/lib/libhardware_legacy.so:system/lib/libhardware_legacy.so \
$(LOCAL_PATH)/system/lib/libhardware.so:system/lib/libhardware.so \
$(LOCAL_PATH)/system/lib/liblog.so:system/lib/liblog.so \
$(LOCAL_PATH)/system/lib/libm.so:system/lib/libm.so \
$(LOCAL_PATH)/system/lib/libOmxAacEnc.so:system/lib/libOmxAacEnc.so \
$(LOCAL_PATH)/system/lib/libOmxAmrEnc.so:system/lib/libOmxAmrEnc.so \
$(LOCAL_PATH)/system/lib/libOmxCore.so:system/lib/libOmxCore.so \
$(LOCAL_PATH)/system/lib/libOmxEvrcEnc.so:system/lib/libOmxEvrcEnc.so \
$(LOCAL_PATH)/system/lib/libOmxQcelp13Enc.so:system/lib/libOmxQcelp13Enc.so \
$(LOCAL_PATH)/system/lib/libOmxVdecHevc.so:system/lib/libOmxVdecHevc.so \
$(LOCAL_PATH)/system/lib/libOmxVdec.so:system/lib/libOmxVdec.so \
$(LOCAL_PATH)/system/lib/libOmxVenc.so:system/lib/libOmxVenc.so \
$(LOCAL_PATH)/system/lib/libOpenMAXAL.so:system/lib/libOpenMAXAL.so \
$(LOCAL_PATH)/system/lib/libOpenSLES.so:system/lib/libOpenSLES.so \
$(LOCAL_PATH)/system/lib/libpower.so:system/lib/libpower.so \
$(LOCAL_PATH)/system/lib/libqcomfm_jni.so:system/lib/libqcomfm_jni.so \
$(LOCAL_PATH)/system/lib/libreference-ril.so:system/lib/libreference-ril.so \
$(LOCAL_PATH)/system/lib/libril.so:system/lib/libril.so \
$(LOCAL_PATH)/system/lib/librilutils.so:system/lib/librilutils.so \
$(LOCAL_PATH)/system/lib/libRScpp.so:system/lib/libRScpp.so \
$(LOCAL_PATH)/system/lib/libRSCpuRef.so:system/lib/libRSCpuRef.so \
$(LOCAL_PATH)/system/lib/libRSDriver.so:system/lib/libRSDriver.so \
$(LOCAL_PATH)/system/lib/librs_jni.so:system/lib/librs_jni.so \
$(LOCAL_PATH)/system/lib/librsjni.so:system/lib/librsjni.so \
$(LOCAL_PATH)/system/lib/libRS.so:system/lib/libRS.so \
$(LOCAL_PATH)/system/lib/libRSSupport.so:system/lib/libRSSupport.so \
$(LOCAL_PATH)/system/lib/libstdc++.so:system/lib/libstdc++.so \
$(LOCAL_PATH)/system/usr/atmel_mxt_ts.kl:system/usr/atmel_mxt_ts.kl \
$(LOCAL_PATH)/system/usr/AVRCP.kl:system/usr/AVRCP.kl \
$(LOCAL_PATH)/system/usr/Generic.kl:system/usr/Generic.kl \
$(LOCAL_PATH)/system/usr/gpio-keys.kl:system/usr/gpio-keys.kl \
$(LOCAL_PATH)/system/usr/synaptics_rmi4_i2c.kl:system/usr/synaptics_rmi4_i2c.kl \
$(LOCAL_PATH)/system/usr/syna-touchscreen.idc:system/usr/syna-touchscreen.idc \
$(LOCAL_PATH)/system/usr/syna-touchscreen.kl:system/usr/syna-touchscreen.kl \
$(LOCAL_PATH)/system/usr/touchscreen-syna.idc:system/usr/touchscreen-syna.idc \
$(LOCAL_PATH)/system/usr/touchscreen-syna.kl:system/usr/touchscreen-syna.kl \
$(LOCAL_PATH)/system/usr/Vendor_0079_Product_0011.kl:system/usr/Vendor_0079_Product_0011.kl \
$(LOCAL_PATH)/system/usr/Vendor_045e_Product_028e.kl:system/usr/Vendor_045e_Product_028e.kl \
$(LOCAL_PATH)/system/usr/Vendor_045e_Product_0719.kl:system/usr/Vendor_045e_Product_0719.kl \
$(LOCAL_PATH)/system/usr/Vendor_046d_Product_b501.kl:system/usr/Vendor_046d_Product_b501.kl \
$(LOCAL_PATH)/system/usr/Vendor_046d_Product_c216.kl:system/usr/Vendor_046d_Product_c216.kl \
$(LOCAL_PATH)/system/usr/Vendor_046d_Product_c219.kl:system/usr/Vendor_046d_Product_c219.kl \
$(LOCAL_PATH)/system/usr/Vendor_046d_Product_c21d.kl:system/usr/Vendor_046d_Product_c21d.kl \
$(LOCAL_PATH)/system/usr/Vendor_046d_Product_c21f.kl:system/usr/Vendor_046d_Product_c21f.kl \
$(LOCAL_PATH)/system/usr/Vendor_046d_Product_c294.kl:system/usr/Vendor_046d_Product_c294.kl \
$(LOCAL_PATH)/system/usr/Vendor_046d_Product_c299.kl:system/usr/Vendor_046d_Product_c299.kl \
$(LOCAL_PATH)/system/usr/Vendor_046d_Product_c532.kl:system/usr/Vendor_046d_Product_c532.kl \
$(LOCAL_PATH)/system/usr/Vendor_054c_Product_0268.kl:system/usr/Vendor_054c_Product_0268.kl \
$(LOCAL_PATH)/system/usr/Vendor_0583_Product_2060.kl:system/usr/Vendor_0583_Product_2060.kl \
$(LOCAL_PATH)/system/usr/Vendor_05ac_Product_0239.kl:system/usr/Vendor_05ac_Product_0239.kl \
$(LOCAL_PATH)/system/usr/Vendor_0b05_Product_4500.kl:system/usr/Vendor_0b05_Product_4500.kl \
$(LOCAL_PATH)/system/usr/Vendor_1038_Product_1412.kl:system/usr/Vendor_1038_Product_1412.kl \
$(LOCAL_PATH)/system/usr/Vendor_12bd_Product_d015.kl:system/usr/Vendor_12bd_Product_d015.kl \
$(LOCAL_PATH)/system/usr/Vendor_1532_Product_0900.kl:system/usr/Vendor_1532_Product_0900.kl \
$(LOCAL_PATH)/system/usr/Vendor_1689_Product_fd00.kl:system/usr/Vendor_1689_Product_fd00.kl \
$(LOCAL_PATH)/system/usr/Vendor_1689_Product_fd01.kl:system/usr/Vendor_1689_Product_fd01.kl \
$(LOCAL_PATH)/system/usr/Vendor_1689_Product_fe00.kl:system/usr/Vendor_1689_Product_fe00.kl \
$(LOCAL_PATH)/system/usr/Vendor_18d1_Product_2c40.kl:system/usr/Vendor_18d1_Product_2c40.kl \
$(LOCAL_PATH)/system/usr/Vendor_1949_Product_0401.kl:system/usr/Vendor_1949_Product_0401.kl \
$(LOCAL_PATH)/system/usr/Vendor_1bad_Product_f016.kl:system/usr/Vendor_1bad_Product_f016.kl \
$(LOCAL_PATH)/system/usr/Vendor_1bad_Product_f023.kl:system/usr/Vendor_1bad_Product_f023.kl \
$(LOCAL_PATH)/system/usr/Vendor_1bad_Product_f027.kl:system/usr/Vendor_1bad_Product_f027.kl \
$(LOCAL_PATH)/system/usr/Vendor_1bad_Product_f036.kl:system/usr/Vendor_1bad_Product_f036.kl \
$(LOCAL_PATH)/system/usr/Vendor_1d79_Product_0009.kl:system/usr/Vendor_1d79_Product_0009.kl \
$(LOCAL_PATH)/system/usr/Vendor_22b8_Product_093d.kl:system/usr/Vendor_22b8_Product_093d.kl \
$(LOCAL_PATH)/system/usr/Vendor_2378_Product_1008.kl:system/usr/Vendor_2378_Product_1008.kl \
$(LOCAL_PATH)/system/usr/Vendor_2378_Product_100a.kl:system/usr/Vendor_2378_Product_100a.kl \
$(LOCAL_PATH)/system/vendor/libadreno_utils.so:system/lib/libadreno_utils.so \
$(LOCAL_PATH)/system/vendor/libaudcal.so:system/lib/libaudcal.so \
$(LOCAL_PATH)/system/vendor/libaudioalsa.so:system/lib/libaudioalsa.so \
$(LOCAL_PATH)/system/vendor/libc2d2_z180.so:system/lib/libc2d2_z180.so \
$(LOCAL_PATH)/system/vendor/libC2D2.so:system/lib/libC2D2.so \
$(LOCAL_PATH)/system/vendor/libbtnv.so:system/lib/libbtnv.so \
$(LOCAL_PATH)/system/vendor/libc2d30-a3xx.so:system/lib/libc2d30-a3xx.so \
$(LOCAL_PATH)/system/vendor/libc2d30-a4xx.so:system/lib/libc2d30-a4xx.so \
$(LOCAL_PATH)/system/vendor/libc2d30.so:system/lib/libc2d30.so \
$(LOCAL_PATH)/system/vendor/libCB.so:system/lib/libCB.so \
$(LOCAL_PATH)/system/vendor/libchromatix_imx132_common.so:system/lib/libchromatix_imx132_common.so \
$(LOCAL_PATH)/system/vendor/libchromatix_imx132_default_video.so:system/lib/libchromatix_imx132_default_video.so \
$(LOCAL_PATH)/system/vendor/libchromatix_imx132_preview.so:system/lib/libchromatix_imx132_preview.so \
$(LOCAL_PATH)/system/vendor/libchromatix_imx132_snapshot.so:system/lib/libchromatix_imx132_snapshot.so \
$(LOCAL_PATH)/system/vendor/libchromatix_imx135_common.so:system/lib/libchromatix_imx135_common.so \
$(LOCAL_PATH)/system/vendor/libchromatix_imx135_default_video.so:system/lib/libchromatix_imx135_default_video.so \
$(LOCAL_PATH)/system/vendor/libchromatix_imx135_hfr_120.so:system/lib/libchromatix_imx135_hfr_120.so \
$(LOCAL_PATH)/system/vendor/libchromatix_imx135_preview.so:system/lib/libchromatix_imx135_preview.so \
$(LOCAL_PATH)/system/vendor/libchromatix_imx135_snapshot.so:system/lib/libchromatix_imx135_snapshot.so \
$(LOCAL_PATH)/system/vendor/libchromatix_imx135_snapshot_ztehdr.so:system/lib/libchromatix_imx135_snapshot_ztehdr.so \
$(LOCAL_PATH)/system/vendor/libchromatix_imx135_snapshot_ztephotosolid.so:system/lib/libchromatix_imx135_snapshot_ztephotosolid.so \
$(LOCAL_PATH)/system/vendor/libchromatix_imx135_video_hd.so:system/lib/libchromatix_imx135_video_hd.so \
$(LOCAL_PATH)/system/vendor/libcneapiclient.so:system/lib/libcneapiclient.so \
$(LOCAL_PATH)/system/vendor/libCommandSvc.so:system/lib/libCommandSvc.so \
$(LOCAL_PATH)/system/vendor/libdiagbridge.so:system/lib/libdiagbridge.so \
$(LOCAL_PATH)/system/vendor/libdiag.so:system/lib/libdiag.so \
$(LOCAL_PATH)/system/vendor/libdisp-aba.so:system/lib/libdisp-aba.so \
$(LOCAL_PATH)/system/vendor/libds_jni.so:system/lib/libds_jni.so \
$(LOCAL_PATH)/system/vendor/libds_native.so:system/lib/libds_native.so \
$(LOCAL_PATH)/system/vendor/libdsnetutils.so:system/lib/libdsnetutils.so \
$(LOCAL_PATH)/system/vendor/libdsucsd.so:system/lib/libdsucsd.so \
$(LOCAL_PATH)/system/vendor/libdsutils.so:system/lib/libdsutils.so \
$(LOCAL_PATH)/system/vendor/libidl.so:system/lib/libidl.so \
$(LOCAL_PATH)/system/vendor/lib-imscamera.so:system/lib/lib-imscamera.so \
$(LOCAL_PATH)/system/vendor/lib-imsdpl.so:system/lib/lib-imsdpl.so \
$(LOCAL_PATH)/system/vendor/lib-imsqimf.so:system/lib/lib-imsqimf.so \
$(LOCAL_PATH)/system/vendor/lib-imsrcs.so:system/lib/lib-imsrcs.so \
$(LOCAL_PATH)/system/vendor/lib-imsSDP.so:system/lib/lib-imsSDP.so \
$(LOCAL_PATH)/system/vendor/lib-imss.so:system/lib/lib-imss.so \
$(LOCAL_PATH)/system/vendor/lib-imsvt.so:system/lib/lib-imsvt.so \
$(LOCAL_PATH)/system/vendor/lib-imsxml.so:system/lib/lib-imsxml.so \
$(LOCAL_PATH)/system/vendor/libizat_core.so:system/lib/libizat_core.so \
$(LOCAL_PATH)/system/vendor/libjpegdhw.so:system/lib/libjpegdhw.so \
$(LOCAL_PATH)/system/vendor/libjpegehw.so:system/lib/libjpegehw.so \
$(LOCAL_PATH)/system/vendor/libllvm-qcom.so:system/lib/libllvm-qcom.so \
$(LOCAL_PATH)/system/vendor/libloc2jnibridge.so:system/lib/libloc2jnibridge.so \
$(LOCAL_PATH)/system/vendor/liblocationservice.so:system/lib/liblocationservice.so \
$(LOCAL_PATH)/system/vendor/libloc_ext.so:system/lib/libloc_ext.so \
$(LOCAL_PATH)/system/vendor/libmm-abl-oem.so:system/lib/libmm-abl-oem.so \
$(LOCAL_PATH)/system/vendor/libmm-abl.so:system/lib/libmm-abl.so \
$(LOCAL_PATH)/system/vendor/libmmcamera2_c2d_module.so:system/lib/libmmcamera2_c2d_module.so \
$(LOCAL_PATH)/system/vendor/libmmcamera2_cpp_module.so:system/lib/libmmcamera2_cpp_module.so \
$(LOCAL_PATH)/system/vendor/libmmcamera2_iface_modules.so:system/lib/libmmcamera2_iface_modules.so \
$(LOCAL_PATH)/system/vendor/libmmcamera2_imglib_modules.so:system/lib/libmmcamera2_imglib_modules.so \
$(LOCAL_PATH)/system/vendor/libmmcamera2_isp_modules.so:system/lib/libmmcamera2_isp_modules.so \
$(LOCAL_PATH)/system/vendor/libmmcamera2_pproc_modules.so:system/lib/libmmcamera2_pproc_modules.so \
$(LOCAL_PATH)/system/vendor/libmmcamera2_sensor_modules.so:system/lib/libmmcamera2_sensor_modules.so \
$(LOCAL_PATH)/system/vendor/libmmcamera2_stats_algorithm.so:system/lib/libmmcamera2_stats_algorithm.so \
$(LOCAL_PATH)/system/vendor/libmmcamera2_stats_modules.so:system/lib/libmmcamera2_stats_modules.so \
$(LOCAL_PATH)/system/vendor/libmmcamera2_vpe_module.so:system/lib/libmmcamera2_vpe_module.so \
$(LOCAL_PATH)/system/vendor/libmmcamera2_wnr_module.so:system/lib/libmmcamera2_wnr_module.so \
$(LOCAL_PATH)/system/vendor/libmmcamera_faceproc.so:system/lib/libmmcamera_faceproc.so \
$(LOCAL_PATH)/system/vendor/libmmcamera_hdr_gb_lib.so:system/lib/libmmcamera_hdr_gb_lib.so \
$(LOCAL_PATH)/system/vendor/libmmcamera_hdr_lib.so:system/lib/libmmcamera_hdr_lib.so \
$(LOCAL_PATH)/system/vendor/libmmcamera_hi256.so:system/lib/libmmcamera_hi256.so \
$(LOCAL_PATH)/system/vendor/libmmcamera_imglib.so:system/lib/libmmcamera_imglib.so \
$(LOCAL_PATH)/system/vendor/libmmcamera_imx132.so:system/lib/libmmcamera_imx132.so \
$(LOCAL_PATH)/system/vendor/libmmcamera_imx135.so:system/lib/libmmcamera_imx135.so \
$(LOCAL_PATH)/system/vendor/libmm-color-convertor.so:system/lib/libmm-color-convertor.so \
$(LOCAL_PATH)/system/vendor/libmmgesture-bus2.so:system/lib/libmmgesture-bus2.so \
$(LOCAL_PATH)/system/vendor/libmm-hdcpmgr.so:system/lib/libmm-hdcpmgr.so \
$(LOCAL_PATH)/system/vendor/liboemcamera.so:system/lib/liboemcamera.so \
$(LOCAL_PATH)/system/vendor/liboi_sbc_decoder.so:system/lib/liboi_sbc_decoder.so \
$(LOCAL_PATH)/system/vendor/libOmxAacDec.so:system/lib/libOmxAacDec.so \
$(LOCAL_PATH)/system/vendor/libOmxAmrwbplusDec.so:system/lib/libOmxAmrwbplusDec.so \
$(LOCAL_PATH)/system/vendor/libOmxEvrcDec.so:system/lib/libOmxEvrcDec.so \
$(LOCAL_PATH)/system/vendor/libOmxMux.so:system/lib/libOmxMux.so \
$(LOCAL_PATH)/system/vendor/libOmxQcelp13Dec.so:system/lib/libOmxQcelp13Dec.so \
$(LOCAL_PATH)/system/vendor/libOmxWmaDec.so:system/lib/libOmxWmaDec.so \
$(LOCAL_PATH)/system/vendor/libOpenCL.so:system/lib/libOpenCL.so \
$(LOCAL_PATH)/system/vendor/libOpenVG.so:system/lib/libOpenVG.so \
$(LOCAL_PATH)/system/vendor/libprofiler_msmadc.so:system/lib/libprofiler_msmadc.so \
$(LOCAL_PATH)/system/vendor/libqcci_legacy.so:system/lib/libqcci_legacy.so \
$(LOCAL_PATH)/system/vendor/libqc-opt.so:system/lib/libqc-opt.so \
$(LOCAL_PATH)/system/vendor/libqdi.so:system/lib/libqdi.so \
$(LOCAL_PATH)/system/vendor/libqdp.so:system/lib/libqdp.so \
$(LOCAL_PATH)/system/vendor/libqmi_cci.so:system/lib/libqmi_cci.so \
$(LOCAL_PATH)/system/vendor/libqmi_client_qmux.so:system/lib/libqmi_client_qmux.so \
$(LOCAL_PATH)/system/vendor/libqmi_common_so.so:system/lib/libqmi_common_so.so \
$(LOCAL_PATH)/system/vendor/libqmi_csi.so:system/lib/libqmi_csi.so \
$(LOCAL_PATH)/system/vendor/libqmi_csvt_srvc.so:system/lib/libqmi_csvt_srvc.so \
$(LOCAL_PATH)/system/vendor/libqmi_encdec.so:system/lib/libqmi_encdec.so \
$(LOCAL_PATH)/system/vendor/libqmiservices.so:system/lib/libqmiservices.so \
$(LOCAL_PATH)/system/vendor/libqmi.so:system/lib/libqmi.so \
$(LOCAL_PATH)/system/vendor/libQSEEComAPI.so:system/lib/libQSEEComAPI.so \
$(LOCAL_PATH)/system/vendor/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
$(LOCAL_PATH)/system/vendor/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
$(LOCAL_PATH)/system/vendor/librs_adreno_sha1.so:system/lib/librs_adreno_sha1.so \
$(LOCAL_PATH)/system/vendor/librs_adreno.so:system/lib/librs_adreno.so \
$(LOCAL_PATH)/system/vendor/libRSDriver_adreno.so:system/lib/libRSDriver_adreno.so \
$(LOCAL_PATH)/system/vendor/lib-rtpcommon.so:system/lib/lib-rtpcommon.so \
$(LOCAL_PATH)/system/vendor/lib-rtpcore.so:system/lib/lib-rtpcore.so \
$(LOCAL_PATH)/system/vendor/lib-rtpdaemoninterface.so:system/lib/lib-rtpdaemoninterface.so \
$(LOCAL_PATH)/system/vendor/lib-rtpsl.so:system/lib/lib-rtpsl.so \
$(LOCAL_PATH)/system/vendor/libsc-a2xx.so:system/lib/libsc-a2xx.so \
$(LOCAL_PATH)/system/vendor/libsc-a3xx.so:system/lib/libsc-a3xx.so \
$(LOCAL_PATH)/system/vendor/libsensor1.so:system/lib/libsensor1.so \
$(LOCAL_PATH)/system/vendor/libsensor_reg.so:system/lib/libsensor_reg.so \
$(LOCAL_PATH)/system/vendor/libsensor_test.so:system/lib/libsensor_test.so \
$(LOCAL_PATH)/system/vendor/libsensor_thresh.so:system/lib/libsensor_thresh.so \
$(LOCAL_PATH)/system/vendor/libsensor_user_cal.so:system/lib/libsensor_user_cal.so \
$(LOCAL_PATH)/system/vendor/libSHIMDivxDrm.so:system/lib/libSHIMDivxDrm.so \
$(LOCAL_PATH)/system/vendor/libsrsprocessing.so:system/lib/libsrsprocessing.so \
$(LOCAL_PATH)/system/vendor/libstagefright_soft_ddpdec.so:system/lib/libstagefright_soft_ddpdec.so \
$(LOCAL_PATH)/system/vendor/libStDrvInt.so:system/lib/libStDrvInt.so \
$(LOCAL_PATH)/system/vendor/libsubsystem_control.so:system/lib/libsubsystem_control.so \
$(LOCAL_PATH)/system/vendor/libSubSystemShutdown.so:system/lib/libSubSystemShutdown.so \
$(LOCAL_PATH)/system/vendor/libsurround_proc.so:system/lib/libsurround_proc.so \
$(LOCAL_PATH)/system/vendor/libthermalclient.so:system/lib/libthermalclient.so \
$(LOCAL_PATH)/system/vendor/libthermalioctl.so:system/lib/libthermalioctl.so \
$(LOCAL_PATH)/system/vendor/libtime_genoff.so:system/lib/libtime_genoff.so \
$(LOCAL_PATH)/system/vendor/libTimeService.so:system/lib/libTimeService.so \
$(LOCAL_PATH)/system/vendor/libvendorconn.so:system/lib/libvendorconn.so \
$(LOCAL_PATH)/system/vendor/libwfdcommonutils.so:system/lib/libwfdcommonutils.so \
$(LOCAL_PATH)/system/vendor/libwfdhdcpcp.so:system/lib/libwfdhdcpcp.so \
$(LOCAL_PATH)/system/vendor/libwfdmmsink.so:system/lib/libwfdmmsink.so \
$(LOCAL_PATH)/system/vendor/libwfdmmsrc.so:system/lib/libwfdmmsrc.so \
$(LOCAL_PATH)/system/vendor/libwfdmmutils.so:system/lib/libwfdmmutils.so \
$(LOCAL_PATH)/system/vendor/libwfdrtsp.so:system/lib/libwfdrtsp.so \
$(LOCAL_PATH)/system/vendor/libwfdsm.so:system/lib/libwfdsm.so \
$(LOCAL_PATH)/system/vendor/libwfduibcinterface.so:system/lib/libwfduibcinterface.so \
$(LOCAL_PATH)/system/vendor/libwfduibcsinkinterface.so:system/lib/libwfduibcsinkinterface.so \
$(LOCAL_PATH)/system/vendor/libwfduibcsink.so:system/lib/libwfduibcsink.so \
$(LOCAL_PATH)/system/vendor/libwfduibcsrcinterface.so:system/lib/libwfduibcsrcinterface.so \
$(LOCAL_PATH)/system/vendor/libwfduibcsrc.so:system/lib/libwfduibcsrc.so \
$(LOCAL_PATH)/system/vendor/libwifiscanner.so:system/lib/libwifiscanner.so \
$(LOCAL_PATH)/system/vendor/libxtwifi_ulp_adaptor.so:system/lib/libxtwifi_ulp_adaptor.so \
$(LOCAL_PATH)/system/xbin/su:system/xbin/su \
$(LOCAL_PATH)/system/vendor/libxtwifi_zpp_adaptor.so:system/lib/libxtwifi_zpp_adaptor.so \
$(LOCAL_PATH)/system/vendor/surround_sound_headers.so:system/lib/surround_sound_headers.so 


